[build-system]
requires = ["setuptools>=74.1"]
build-backend = "setuptools.build_meta"

[project]
name = "heap"
version = "1.00"

[tool.setuptools]
ext-modules = [{name = "heap", sources = ["internals/lib/_heapify.c"]}]