# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

env:
  APP_ENV: 'dev'

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  test:

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_DB: dev_rare_treasures
          POSTGRES_USER: dev_user
          POSTGRES_PASSWORD: dev_password
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U dev_user" 
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.13
        uses: actions/setup-python@v3
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Set environment variables
        run: |
          touch rare_treasures_api/.env.dev

          cat << EOF > rare_treasures_api/.env.dev
              PG_DATABASE = dev_rare_treasures
              PG_USER = dev_user
              PG_PASSWORD = dev_password
              PG_HOST = localhost
              PG_PORT = 5432
          EOF

      - name: Lint with pylint
        run: |
          pylint */src --fail-under=8

      - name: Coverage with pytest
        run: |
          pytest --cov=. */tests --cov-fail-under=80

      - name: Test with pytest
        run: |
          pytest
