# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.13
        uses: actions/setup-python@v3
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Set environment variables
        run: |
          touch .env.dev
          echo PG_DATABASE = ${{ secrets.PG_DATABASE }} >> .env.dev
          echo PG_USER = ${{ secrets.PG_USER }} >> .env.dev
          echo PG_PASSWORD = ${{ secrets.PG_PASSWORD }} >> .env.dev
          echo PG_HOST = ${{ secrets.PG_HOST }} >> .env.dev
          echo PG_PORT = 5432 >> .env.dev

      - name: Test with pytest
        run: |
          pytest rare_treasures_api/tests
